name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
