name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install firebase tools
        run: npm install firebase-tools -g

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: firebase deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASTE_1C305 }}
