name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install firebase
        run: npm i firebase-tools -g

      - name: deploy
        run: firebase deploy
